export const SCRAPE_RECIPE_PENDING = "SCRAPE_RECIPE_PENDING";

export const SCRAPE_RECIPE_SUCCESS = "SCRAPE_RECIPE_SUCCESS";

export const SCRAPE_RECIPE_FAILURE = "SCRAPE_RECIPE_FAILURE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_RECIPES_PENDING = "GET_RECIPES_PENDING";

export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";

export const GET_RECIPES_FAILURE = "GET_RECIPES_FAILURE";
