export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SCRAPE_RECIPE_PENDING = "SCRAPE_RECIPE_PENDING";

export const SCRAPE_RECIPE_SUCCESS = "SCRAPE_RECIPE_SUCCESS";

export const SCRAPE_RECIPE_FAILURE = "SCRAPE_RECIPE_FAILURE";

export const SCRAPE_RECIPE_RESET = "SCRAPE_RECIPE_RESET";

export const GET_RECIPES_PENDING = "GET_RECIPES_PENDING";

export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";

export const GET_RECIPES_FAILURE = "GET_RECIPES_FAILURE";

export const DELETE_RECIPE_PENDING = "GET_RECIPE_PENDING";

export const DELETE_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";

export const DELETE_RECIPE_FAILURE = "GET_RECIPE_FAILURE";
